# Generated by Django 6.0 on 2026-01-04 03:34

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agency',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('plan_level', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'agencies',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='IGAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.TextField()),
                ('status', models.TextField(default='ACTIVE')),
                ('cookies', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'ig_accounts',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='InteractionCampaign',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='Campaign', max_length=200)),
                ('action', models.CharField(choices=[('LIKE', 'LIKE'), ('COMMENT', 'COMMENT')], max_length=10)),
                ('status', models.CharField(choices=[('DRAFT', 'DRAFT'), ('QUEUED', 'QUEUED'), ('RUNNING', 'RUNNING'), ('PAUSED', 'PAUSED'), ('DONE', 'DONE'), ('FAILED', 'FAILED')], default='QUEUED', max_length=10)),
                ('post_urls', models.JSONField(default=list)),
                ('comment_mode', models.CharField(blank=True, max_length=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('agency', models.ForeignKey(db_column='agency_id', on_delete=django.db.models.deletion.CASCADE, to='automation.agency')),
            ],
            options={
                'db_table': 'interaction_campaigns',
            },
        ),
        migrations.CreateModel(
            name='InteractionTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('LIKE', 'LIKE'), ('COMMENT', 'COMMENT')], max_length=10)),
                ('post_url', models.TextField()),
                ('comment_text', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('IN_PROGRESS', 'IN_PROGRESS'), ('SUCCESS', 'SUCCESS'), ('ERROR', 'ERROR'), ('RETRY', 'RETRY')], default='PENDING', max_length=15)),
                ('attempts', models.IntegerField(default=0)),
                ('next_retry_at', models.DateTimeField(blank=True, null=True)),
                ('error_code', models.CharField(blank=True, max_length=50, null=True)),
                ('result_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('agency', models.ForeignKey(db_column='agency_id', on_delete=django.db.models.deletion.CASCADE, to='automation.agency')),
                ('campaign', models.ForeignKey(db_column='campaign_id', on_delete=django.db.models.deletion.CASCADE, to='automation.interactioncampaign')),
                ('ig_account', models.ForeignKey(db_column='ig_account_id', on_delete=django.db.models.deletion.CASCADE, to='automation.igaccount')),
            ],
            options={
                'db_table': 'interaction_tasks',
                'indexes': [models.Index(fields=['campaign'], name='interaction_campaig_ed1edd_idx'), models.Index(fields=['status', 'next_retry_at'], name='interaction_status_28f2dd_idx'), models.Index(fields=['ig_account'], name='interaction_ig_acco_728165_idx')],
                'constraints': [models.UniqueConstraint(fields=('campaign', 'ig_account', 'action', 'post_url'), name='uq_task_unique_action')],
            },
        ),
    ]
