# Generated by Django 6.0 on 2025-12-30 05:36

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agency',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('plan_level', models.CharField(choices=[('basic', 'Basic'), ('pro', 'Pro')], default='basic', max_length=50)),
                ('payment_status', models.CharField(default='unpaid', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_account', models.CharField(max_length=100)),
                ('ig_username', models.CharField(max_length=100, unique=True)),
                ('data', models.JSONField(default=dict)),
                ('status', models.CharField(default='to_contact', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Proxy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ip_address', models.GenericIPAddressField()),
                ('port', models.IntegerField()),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='IGAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('password_encrypted', models.BinaryField()),
                ('session_id', models.TextField(blank=True, null=True)),
                ('status', models.CharField(default='active', max_length=50)),
                ('config', models.JSONField(default=dict)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='automation.agency')),
                ('proxy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='automation.proxy')),
            ],
        ),
    ]
