# Generated by Django 6.0 on 2026-01-08 06:56

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agency',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('plan_level', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'agencies',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SystemLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(default='INFO', max_length=20)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'system_logs',
            },
        ),
        migrations.CreateModel(
            name='IGAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.TextField()),
                ('status', models.TextField(default='ACTIVE')),
                ('session_id', models.TextField(blank=True, null=True)),
                ('cookies', models.JSONField(blank=True, default=dict)),
                ('proxy_host', models.CharField(blank=True, default='', max_length=255)),
                ('proxy_port', models.PositiveIntegerField(blank=True, null=True)),
                ('proxy_user', models.CharField(blank=True, default='', max_length=255)),
                ('proxy_password', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agency', models.ForeignKey(blank=True, db_column='agency_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='automation.agency')),
            ],
            options={
                'db_table': 'ig_accounts',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='InteractionCampaign',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='Campaign', max_length=200)),
                ('action', models.CharField(choices=[('LIKE', 'LIKE'), ('COMMENT', 'COMMENT')], max_length=10)),
                ('status', models.CharField(choices=[('DRAFT', 'DRAFT'), ('QUEUED', 'QUEUED'), ('RUNNING', 'RUNNING'), ('PAUSED', 'PAUSED'), ('DONE', 'DONE'), ('FAILED', 'FAILED')], default='QUEUED', max_length=10)),
                ('target_url', models.URLField()),
                ('bot_count', models.PositiveIntegerField(default=1)),
                ('post_urls', models.JSONField(default=list)),
                ('comment_mode', models.CharField(blank=True, choices=[('AI', 'AI'), ('MANUAL', 'MANUAL')], default='MANUAL', max_length=10)),
                ('manual_comments', models.TextField(blank=True, default='')),
                ('ai_persona', models.CharField(blank=True, max_length=255)),
                ('ai_tone', models.CharField(blank=True, max_length=100)),
                ('ai_user_prompt', models.TextField(blank=True)),
                ('ai_use_image_context', models.BooleanField(default=False)),
                ('ai_provider', models.CharField(choices=[('GEMINI', 'Gemini'), ('OLLAMA', 'Ollama')], default='OLLAMA', max_length=20)),
                ('ollama_model', models.CharField(default='ministral-3:8b', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('agency', models.ForeignKey(db_column='agency_id', on_delete=django.db.models.deletion.CASCADE, to='automation.agency')),
            ],
            options={
                'db_table': 'interaction_campaigns',
            },
        ),
        migrations.CreateModel(
            name='InteractionTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('LIKE', 'LIKE'), ('COMMENT', 'COMMENT')], max_length=10)),
                ('post_url', models.TextField()),
                ('comment_text', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('IN_PROGRESS', 'IN_PROGRESS'), ('SUCCESS', 'SUCCESS'), ('ERROR', 'ERROR'), ('RETRY', 'RETRY')], default='PENDING', max_length=15)),
                ('attempts', models.IntegerField(default=0)),
                ('next_retry_at', models.DateTimeField(blank=True, null=True)),
                ('error_code', models.CharField(blank=True, max_length=50, null=True)),
                ('result_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('agency', models.ForeignKey(db_column='agency_id', on_delete=django.db.models.deletion.CASCADE, to='automation.agency')),
                ('campaign', models.ForeignKey(db_column='campaign_id', on_delete=django.db.models.deletion.CASCADE, to='automation.interactioncampaign')),
                ('ig_account', models.ForeignKey(db_column='ig_account_id', on_delete=django.db.models.deletion.CASCADE, to='automation.igaccount')),
            ],
            options={
                'db_table': 'interaction_tasks',
                'indexes': [models.Index(fields=['campaign'], name='interaction_campaig_ed1edd_idx'), models.Index(fields=['status', 'next_retry_at'], name='interaction_status_28f2dd_idx'), models.Index(fields=['ig_account'], name='interaction_ig_acco_728165_idx')],
                'constraints': [models.UniqueConstraint(fields=('campaign', 'ig_account', 'action', 'post_url'), name='uq_task_unique_action')],
            },
        ),
    ]
