# Generated by Django 6.0 on 2026-01-04 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0002_interactioncampaign_ai_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interactioncampaign',
            name='ai_persona',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='interactioncampaign',
            name='ai_tone',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='interactioncampaign',
            name='ai_user_prompt',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='interactioncampaign',
            name='comment_mode',
            field=models.CharField(blank=True, choices=[('AI', 'AI'), ('MANUAL', 'MANUAL')], default='MANUAL', max_length=10),
        ),
        migrations.AlterField(
            model_name='interactioncampaign',
            name='manual_comments',
            field=models.TextField(blank=True),
        ),
    ]
