# Generated by Django 6.0 on 2026-01-03 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0002_systemlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='igaccount',
            name='last_used',
            field=models.DateTimeField(blank=True, help_text='Marca de tiempo para calcular enfriamiento', null=True),
        ),
    ]
