# Generated by Django 6.0 on 2026-01-09 02:16

import automation.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0002_alter_agency_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interactioncampaign',
            name='action',
            field=models.CharField(choices=[('LIKE', 'LIKE'), ('COMMENT', 'COMMENT'), ('FOLLOW', 'FOLLOW'), ('LIKE_COMMENT', 'LIKE_COMMENT')], max_length=20),
        ),
        migrations.AlterField(
            model_name='interactioncampaign',
            name='ai_provider',
            field=models.CharField(choices=[('GEMINI', 'Gemini'), ('OLLAMA', 'Ollama')], default=automation.models.get_ai_provider_default, max_length=20),
        ),
        migrations.AlterField(
            model_name='interactioncampaign',
            name='ollama_model',
            field=models.CharField(default=automation.models.get_ollama_default_model, max_length=100),
        ),
        migrations.AlterField(
            model_name='interactioncampaign',
            name='target_url',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='interactiontask',
            name='action',
            field=models.CharField(choices=[('LIKE', 'LIKE'), ('COMMENT', 'COMMENT'), ('FOLLOW', 'FOLLOW'), ('LIKE_COMMENT', 'LIKE_COMMENT')], max_length=20),
        ),
    ]
