# Generated by Django 6.0 on 2026-01-07 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0007_update_ai_provider_defaults'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(default='INFO', max_length=20)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'system_logs',
            },
        ),
        migrations.AlterField(
            model_name='interactioncampaign',
            name='ai_provider',
            field=models.CharField(choices=[('GEMINI', 'Gemini'), ('OLLAMA', 'Ollama')], default='OLLAMA', max_length=20),
        ),
        migrations.AlterField(
            model_name='interactioncampaign',
            name='ollama_model',
            field=models.CharField(default='ministral-3:8b', max_length=100),
        ),
    ]
