# Generated by Django 6.0 on 2026-01-08 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0008_systemlog_alter_interactioncampaign_ai_provider_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='igaccount',
            options={'managed': True},
        ),
    ]
