# Generated by Django 6.0 on 2026-01-08 05:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0009_alter_igaccount_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='igaccount',
            name='agency',
            field=models.ForeignKey(blank=True, db_column='agency_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='automation.agency'),
        ),
        migrations.AddField(
            model_name='igaccount',
            name='session_id',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='igaccount',
            name='cookies',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='igaccount',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
